<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="SignalR01._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

  <div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
  </div>
  <!--Script references. -->
  <!--Reference the jQuery library. -->
  <script src="Scripts/jquery-1.10.2.min.js"></script>
  <!--Reference the SignalR library. -->
  <script src="Scripts/jquery.signalR-2.2.1.min.js"></script>
  <!--Reference the autogenerated SignalR hub script. -->
  <script src="signalr/hubs"></script>
  <!--Add script to update the page and send messages.-->
  <script type="text/javascript">
    $(function () {
      // Declare a proxy to reference the hub.
      var chat = $.connection.chatHub;
      // Create a function that the hub can call to broadcast messages.
      chat.client.broadcastMessage = function (name, message) {
        // Html encode display name and message.
        var encodedName = $('<div />').text(name).html();
        var encodedMsg = $('<div />').text(message).html();
        // Add the message to the page.
        $('#discussion').append('<li><strong>' + encodedName
          + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
      };
      // Get the user name and store it to prepend to messages.
      $('#displayname').val(prompt('Enter your name:', ''));
      // Set initial focus to message input box.
      $('#message').focus();
      // Start the connection.
      $.connection.hub.start().done(function () {
        $('#sendmessage').click(function () {
          // Call the Send method on the hub.
          chat.server.send($('#displayname').val(), $('#message').val());
          // Clear text box and reset focus for next comment.
          $('#message').val('').focus();
        });
      });
    });
  </script>

  


  <dx:webchartcontrol id="WebChartControl1" runat="server" height="400px"
    width="700px" onobjectselected="WebChartControl1_ObjectSelected" cssclass="AlignCenter TopLargeMargin"
    clientinstancename="chart" oncustomcallback="WebChartControl1_CustomCallback1"
    tooltipenabled="False">
        <SeriesSerializable>
            <dx:Series Name="Area of Countries" LegendTextPattern="{A}">
                <Points>
                    <dx:SeriesPoint Values="17.0752" ArgumentSerializable="Russia" SeriesPointID="0"></dx:SeriesPoint>
                    <dx:SeriesPoint Values="9.98467" ArgumentSerializable="Canada" SeriesPointID="1"></dx:SeriesPoint>
                    <dx:SeriesPoint Values="9.63142" ArgumentSerializable="USA" SeriesPointID="2"></dx:SeriesPoint>
                    <dx:SeriesPoint Values="9.59696" ArgumentSerializable="China" SeriesPointID="3"></dx:SeriesPoint>
                    <dx:SeriesPoint Values="8.511965" ArgumentSerializable="Brazil" SeriesPointID="4"></dx:SeriesPoint>
                    <dx:SeriesPoint Values="7.68685" ArgumentSerializable="Australia" SeriesPointID="5"></dx:SeriesPoint>
                    <dx:SeriesPoint Values="3.28759" ArgumentSerializable="India" SeriesPointID="6"></dx:SeriesPoint>
                    <dx:SeriesPoint Values="81.2" ArgumentSerializable="Others" SeriesPointID="7"></dx:SeriesPoint>
                </Points>
                <ViewSerializable>
                    <dx:PieSeriesView Rotation="90" RuntimeExploding="True"></dx:PieSeriesView>
                </ViewSerializable>
                <LabelSerializable>
                    <dx:PieSeriesLabel Position="Radial" ColumnIndent="20" TextColor="Black" BackColor="Transparent" Font="Tahoma, 8pt, style=Bold" TextPattern="{VP:P0}">
                        <Border Visibility="False"></Border>
                    </dx:PieSeriesLabel>
                </LabelSerializable>
            </dx:Series>
        </SeriesSerializable>
        <ClientSideEvents
            ObjectSelected="function(s, e) {
                                var hitInPie = e.hitInfo.inSeries &amp;&amp; !e.hitInfo.inLegend; 
                                if(hitInPie) {
                                    var itemCount = cbExplodedPoints.GetItemCount();
                                    cbExplodedPoints.SetSelectedIndex(itemCount - 1);
                                }
                                e.processOnServer = hitInPie;
                            }"
            ObjectHotTracked="function(s, e) {
                                var hitInPie = e.hitInfo.inSeries &amp;&amp; !e.hitInfo.inLegend;
                                s.SetCursor(hitInPie ? 'pointer' : 'default');
                            }" />
        <BorderOptions Visibility="False" />
        <Titles>
            <dx:ChartTitle Text="Area of Countries"></dx:ChartTitle>
            <dx:ChartTitle Dock="Bottom" Alignment="Far" Text="From www.nationmaster.com" Font="Tahoma, 8pt" TextColor="Gray"></dx:ChartTitle>
        </Titles>
        <DiagramSerializable>
            <dx:SimpleDiagram></dx:SimpleDiagram>
        </DiagramSerializable>
    </dx:webchartcontrol>



</asp:Content>
