<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Monitor.aspx.cs" Inherits="SignalR01.Monitor" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


  <!--Script references. -->
  <!--Reference the jQuery library. -->
  <script src="Scripts/jquery-1.10.2.min.js"></script>
  <!--Reference the SignalR library. -->
  <script src="Scripts/jquery.signalR-2.2.1.min.js"></script>
  <!--Reference the autogenerated SignalR hub script. -->
  <script src="signalr/hubs"></script>
  <!--Add script to update the page and send messages.-->
  <script type="text/javascript">
    $(function () {
      // Declare a proxy to reference the hub.
      var chat = $.connection.chatHub;
      // Create a function that the hub can call to broadcast messages.
      chat.client.broadcastMessage = function (name, message) {
        // Html encode display name and message.
        var encodedName = $('<div />').text(name).html();
        var encodedMsg = $('<div />').text(message).html();
        // Add the message to the page.
        $('#discussion').prepend('<li><strong>' + encodedName
          + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');

        //alert("Got a message");

        //Process the message and set the Progress percentage
        myTEMMessageCallBack.SendCallback(message);

        //Refresh the chart
        ChartCallbackPanel1.PerformCallback();


      };
      // Get the user name and store it to prepend to messages.
      $('#displayname').val(prompt('Enter your name:', ''));
      // Set initial focus to message input box.
      $('#message').focus();
      // Start the connection.
      $.connection.hub.start().done(function () {
        $('#sendmessage').click(function () {
          // Call the Send method on the hub.
          chat.server.send($('#displayname').val(), $('#message').val());
          // Clear text box and reset focus for next comment.
          $('#message').val('').focus();
        });
      });
    });

    var postponedCallbackRequired = true;
    function OnEndChartCallback(s, e) {
      if (postponedCallbackRequired) {
        CallbackPanel.PerformCallback();
        postponedCallbackRequired = false;
      }
    }


    function SendCommentCallback(s, e) {
      CommentCallbackPanel.PerformCallback();
    };

    function OnBeginCallback(s, e) {
      LoadingPanel.Show();
    };

    function OnEndCallback(s, e) {
      LoadingPanel.Hide();
    };

  </script>


  <h2>Report Monitor</h2>

  <dx:ASPxCallbackPanel runat="server" ID="ChartCallbackPanel1"
    Height="250px" ClientInstanceName="ChartCallbackPanel1"
    EnableCallbackAnimation="true"
    RenderMode="Table">
    <ClientSideEvents EndCallback="OnEndChartCallback"></ClientSideEvents>
    <PanelCollection>
      <dx:PanelContent ID="PanelContent3" runat="server">

        <dx:WebChartControl ID="WebChartControl1" runat="server" Height="400px"
          Width="700px" CssClass="AlignCenter TopLargeMargin"
          ClientInstanceName="chart"
          ToolTipEnabled="False">
          <SeriesSerializable>
            <dx:Series Name="Test dynamic chart update using SignalR" LegendTextPattern="{A}">
              <Points>
                <dx:SeriesPoint Values="0" ArgumentSerializable="Completed" SeriesPointID="0"></dx:SeriesPoint>
                <dx:SeriesPoint Values="100" ArgumentSerializable="Working" SeriesPointID="1"></dx:SeriesPoint>
              </Points>
              <ViewSerializable>
                <dx:PieSeriesView Rotation="90" RuntimeExploding="False"></dx:PieSeriesView>
              </ViewSerializable>
              <LabelSerializable>
                <dx:PieSeriesLabel Position="Radial" ColumnIndent="20" TextColor="Black" BackColor="Transparent" Font="Tahoma, 8pt, style=Bold" TextPattern="{VP:P0}">
                  <Border Visibility="False"></Border>
                </dx:PieSeriesLabel>
              </LabelSerializable>
            </dx:Series>
          </SeriesSerializable>
          <BorderOptions Visibility="False" />
          <Titles>
            <dx:ChartTitle Text="Test dynamic chart update using SignalR"></dx:ChartTitle>
            <dx:ChartTitle Dock="Bottom" Alignment="Far" Text="SignalR Proof of Concept" Font="Tahoma, 8pt" TextColor="Gray"></dx:ChartTitle>
          </Titles>
          <DiagramSerializable>
            <dx:SimpleDiagram></dx:SimpleDiagram>
          </DiagramSerializable>
        </dx:WebChartControl>

      </dx:PanelContent>
    </PanelCollection>
  </dx:ASPxCallbackPanel>




  <dx:ASPxCallback ID="ASPxCallback1" runat="server" ClientInstanceName="myTEMMessageCallBack"
    OnCallback="ASPxCallback1_Callback">
    <%--<ClientSideEvents CallbackComplete="OnCallbackComplete" />--%>
  </dx:ASPxCallback>


  <div class="container" style="border: 2px solid #f0f0f0; margin: 40px 0 60px; padding: 10px;">
    <dx:ASPxLabel ID="lblMessage" runat="server" Text="Enter a message (number 0-100 to update pie chart)"></dx:ASPxLabel>
    <br />
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
  </div>

  <div class="sendCommentBlock" style="border: 2px solid #f0f0f0; margin: 40px 0 60px; padding: 10px;">
    <dx:ASPxButton ID="Button" runat="server" Text="Post Comment" AutoPostBack="false">
      <ClientSideEvents Click="SendCommentCallback" />
    </dx:ASPxButton>
    <br />
    <br />
    <dx:ASPxTextBox ID="TextBox" runat="server" Width="170px"></dx:ASPxTextBox>
  </div>

  <div style="border: 2px solid #f0f0f0; margin: 40px 0 60px; padding: 10px;">
    <dx:ASPxCallbackPanel ID="CallbackPanel" ClientInstanceName="CommentCallbackPanel"
      runat="server"
      CssClass="pnl"
      Width="300px"
      OnCallback="CallbackPanel_Callback"
      OnInit="CallbackPanel_Init">
      <SettingsLoadingPanel Enabled="false" />
      <ClientSideEvents BeginCallback="OnBeginCallback" EndCallback="OnEndCallback" />
      <PanelCollection>
        <dx:PanelContent>
          <dx:ASPxLabel ID="CountLabel" runat="server" Text="Comments Count : "></dx:ASPxLabel>
          <br />
          <br />
          <dx:ASPxLabel ID="NoCommentsLabel" runat="server" Text="No Comments" ForeColor="Gray"></dx:ASPxLabel>
        </dx:PanelContent>
      </PanelCollection>
    </dx:ASPxCallbackPanel>
  </div>

  <dx:ASPxLoadingPanel ID="LoadingPanel" ClientInstanceName="LoadingPanel"
    runat="server"
    Modal="true"
    HorizontalAlign="Center"
    VerticalAlign="Middle">
    <Image Url="Images/load.gif" Height="50px" Width="50px"></Image>
  </dx:ASPxLoadingPanel>

</asp:Content>
